{
 "title": "WebAppAzure - docker-fiap.azurewebsites.net",
 "time": { "from": "2023-10-13T22:18:19.287Z", "to": "2023-10-13T22:28:19.287Z" },
 "panels": [
  {
   "title": "WebApp Azure",
   "type": "text",
   "description": "Application Web App Docker Test Fiap ",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "# Application Web App Azure Test Fiap \n\n\nhttp://docker-fiap.azurewebsites.net/\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "CPU Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuTime",
      "metricNamespace": "microsoft.web/sites",
      "region": "eastus",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "eastus",
        "resourceGroup": "kb8s-vm-resource-group",
        "resourceName": "docker-fiap",
        "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
    }
   ]
  },
  {
   "title": "HealthCheckStatus",
   "type": "stat",
   "description": "OK",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       300000,
       3600000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HealthCheckStatus",
      "metricNamespace": "microsoft.web/sites",
      "region": "eastus",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "eastus",
        "resourceGroup": "kb8s-vm-resource-group",
        "resourceName": "docker-fiap",
        "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "region": "eastus",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "eastus",
        "resourceGroup": "kb8s-vm-resource-group",
        "resourceName": "docker-fiap",
        "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "region": "eastus",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "eastus",
        "resourceGroup": "kb8s-vm-resource-group",
        "resourceName": "docker-fiap",
        "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
    }
   ]
  },
  {
   "title": "Taxa de Erros",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http5xx",
      "metricNamespace": "microsoft.web/sites",
      "region": "eastus",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "eastus",
        "resourceGroup": "kb8s-vm-resource-group",
        "resourceName": "docker-fiap",
        "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "c6a5ba67-682a-42ba-b850-e16c1aa8d265"
    }
   ]
  }
 ]
}